project:
  type: book
language: custom.yml
date-format: "DD.MM.YY"
book:
  title: "Politička Analiza"
  subtitle: "Beleške za predavanja"
  author: "Aleksandar Tomašević"
  date: today
  chapters:
    - index.qmd
    - uvod.qmd
    - demokratije.qmd
    - references.qmd

bibliography: references.bib
csl: apa.csl
format:
  html:
   theme: journal
   #theme: zephyr
   #theme: united
  pdf:
    documentclass: scrreprt

citation:
  type: book
  container-title: "Politička Analiza - Skripta"
  url: pa.atomasevic.com
