project:
  type: book
language: custom.yml
date-format: "DD.MM.YY"
book:
  title: "Sociologija politike - Beleške"
  author: "Aleksandar Tomašević"
  date: today
  chapters:
    - index.qmd
    - demokratije.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
   #theme: journal
   #theme: zephyr
   theme: united
  pdf:
    documentclass: scrreprt

citation:
  type: book
  container-title: "Sociologija politike - Skripta"
  url: sp.atomasevic.com
